name: "Docker Checker"
description: "Check if the docker image is running properly"

on:
  push:
    branches: [ main ]

jobs:
  check_docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build -t my-nginx .

      - name: Run Container and Test
        run: |
          docker run -d -p 8080:80 --name web my-nginx
          sleep 5
          curl -f http://localhost:8080
        
      - name: Validate data inside the Container
        run: |
          if echo "$response" | grep -qi "Yahia Elboukili Â· Built & Deployed on AWS"; then
            echo "Content validation passed"
          else
            echo "Expected content not found"
            exit 1
          fi

      - name: cleanup
        if: always()
        run: docker -rm -f web || true

